apiVersion: v1
kind: Secret
metadata:
  name: dete-secrets
  labels:
    {{- include "dete.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
