-- DETE schema initialisation
-- Each service owns its own schema within the shared Postgres instance.
-- Services create their own tables via Flyway on startup.

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS account;
CREATE SCHEMA IF NOT EXISTS order_svc;
CREATE SCHEMA IF NOT EXISTS market_data;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS risk;

GRANT ALL PRIVILEGES ON SCHEMA auth        TO dete;
GRANT ALL PRIVILEGES ON SCHEMA account     TO dete;
GRANT ALL PRIVILEGES ON SCHEMA order_svc   TO dete;
GRANT ALL PRIVILEGES ON SCHEMA market_data TO dete;
GRANT ALL PRIVILEGES ON SCHEMA audit       TO dete;
GRANT ALL PRIVILEGES ON SCHEMA risk        TO dete;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth        GRANT ALL ON TABLES TO dete;
ALTER DEFAULT PRIVILEGES IN SCHEMA account     GRANT ALL ON TABLES TO dete;
ALTER DEFAULT PRIVILEGES IN SCHEMA order_svc   GRANT ALL ON TABLES TO dete;
ALTER DEFAULT PRIVILEGES IN SCHEMA market_data GRANT ALL ON TABLES TO dete;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit       GRANT ALL ON TABLES TO dete;
ALTER DEFAULT PRIVILEGES IN SCHEMA risk        GRANT ALL ON TABLES TO dete;
