FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
ENV JAVA_OPTS="-Xms128m -Xmx256m -XX:+UseG1GC -XX:MaxGCPauseMillis=20"
ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar app.jar"]
